/** Ausrüstungs-Stammdaten für Tests (AP-09a): Starfront mit GT81 und Ares-M Pro. */
import type {
  CameraInput,
  FilterInput,
  MoonProfileInput,
  RigInput,
  SchedulerSettings,
  SiteInput,
  TelescopeInput,
} from '@nina-pm/shared';

export const SITE: SiteInput = {
  name: 'Starfront',
  pierName: null,
  observatoryType: 'remote_hosted',
  latitudeDeg: 31.5471,
  longitudeDeg: -99.3823,
  elevationM: 500,
  bortleClass: 1,
  timeZone: 'America/Chicago',
  weatherSafetyUrl: null,
  notes: '',
};

export const TELESCOPE: TelescopeInput = {
  name: 'GT81',
  brand: 'William Optics',
  model: 'GT81 IV',
  opticalDesign: 'apochromatic_refractor',
  apertureMm: 81,
  focalLengthMm: 478,
  reducerFactor: 0.8,
  obstructionPct: 0,
  imageCircleMm: null,
  backfocusMm: null,
  weightKg: null,
  notes: '',
};

export const CAMERA: CameraInput = {
  name: 'Ares-M Pro',
  brand: 'Player One',
  model: 'Ares-M Pro',
  sensorName: 'IMX533',
  widthPx: 3008,
  heightPx: 3008,
  pixelSizeUm: 3.76,
  bitDepth: 14,
  isCooled: true,
  coolingSetpointC: -10,
  coolingToleranceC: 1,
  isColor: false,
  readNoiseE: 1.0,
  fullWellE: 50000,
  gainEPerAdu: 1.0,
  quantumEfficiencyPct: 80,
  darkCurrentES20c: 0.005,
  defaultGain: null,
  defaultOffset: null,
  defaultBinning: 1,
  defaultReadoutMode: 'Default',
  supportedBinning: [1, 2],
  gainModes: [],
  readoutModes: ['Default'],
  notes: '',
};

export const MOON: MoonProfileInput = {
  name: 'Eigenes',
  description: '',
  separationDeg: 60,
  widthDays: 5,
  relaxScale: 2,
  moonMinAltDeg: -15,
  moonMaxAltDeg: 5,
  maxIlluminationPct: 60,
  moonMustBeDown: false,
};

export const filterInput = (shortName: string): FilterInput => ({
  shortName,
  fullName: '',
  brand: '',
  filterType: 'broadband',
  telescopeId: null,
  size: null,
  shape: null,
  mountType: null,
  bandwidthNm: null,
  centerWavelengthNm: null,
  photometricBand: 'none',
  transmissionPct: null,
  thicknessMm: null,
  colorHex: '#CCCCCC',
  defaultOnNewProject: false,
  defaultExposureS: null,
  defaultMoonProfileId: null,
  notes: '',
});

export const rigInput = (siteId: string, telescopeId: string, cameraId: string): RigInput => ({
  name: 'Starfront – GT81 – Ares-M Pro',
  siteId,
  telescopeId,
  cameraId,
  showInPlanning: true,
  ninaDeliveryEnabled: true,
  defaultTemplateId: null,
  defaultRotationDeg: null,
  hasRotator: false,
  rotationToleranceDeg: 5,
  skipOnRotationMismatch: false,
  sessionReportDiscord: false,
  notes: '',
});

export const SCHEDULER: SchedulerSettings = {
  strategy: 'proportional',
  playback: 'time_aware',
  sortChain: ['lowest_peak_altitude', 'setting_soonest', 'most_remaining', 'constrained'],
  bonusEnabled: false,
  overshootPct: 0,
  mosaicPanelsIndependent: true,
  ditherEnabled: true,
  ditherEvery: 1,
  filterSwitchEnabled: false,
  filterSwitchEvery: 10,
  filterSwitchTolerancePct: 50,
  flatsEnabled: false,
  flatsFullSet: false,
  flatCount: 20,
  darkFlatsEnabled: true,
  darkFlatCount: null,
  flatsSource: 'panel',
  flipEnabled: true,
  flipAfterMeridianMin: 5,
  flipMaxAfterMeridianMin: 15,
  flipPauseBeforeMeridianMin: 0,
  flipDurationS: 240,
  overhead: {
    slewCenterS: 120,
    filterChangeS: 10,
    ditherSettleS: 20,
    afEveryMin: 60,
    afDurationS: 180,
    downloadS: 5,
  },
};
